services:

  api:
    build: ./backend
    container_name: request-inspector-service
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: request-inspector-ui
    ports:
      - "80:80"